# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - link_1
      - link_2
      - link_3
      - link_4
      - link_5
  gripper_controller:
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - link_6
      - link_6